Algoritmo "semnome"
// Faça um programa que receba quatro números inteiros, calcule e mostre a soma
// deses números.
Var
// Seção de Declarações das variáveis 
   soma, num, i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para i de 1 ate 4 faca
        escreva("Digite o",i,"º valor: ")
        leia(num)
        
        soma <- soma + num
   fimpara
   
   escreva("A soma entre os valores digitados é ",soma)

Fimalgoritmo