Algoritmo "semnome"
//Faça um programa que calcule e mostre a área de um triangulo. Sabe-se que: Área = (base * altura) / 2
Var
// Seção de Declarações das variáveis 
   base, altura, area : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite a altura do triângulo: ")
   leia(altura)
   
   escreva("Digite a base do triângulo: ")
   leia(base)

   area <- (base * altura) / 2
   
   escreva("A area é ",area)
Fimalgoritmo